- name: Gather Package facts
  package_facts:
    manager: auto
  tags: [ finish ]

#- debug:
#    var: "{{ item }} is installed"
#  when: "{{ item }} in ansible_facts.packages"
#  with_items:
#    - mariadb-server
#    - nginx
#    - php
#  tags: [ finish ]

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  tags: [ finish ]

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  ignore_errors: yes
  tags: [ finish ]

# Example that prints two lines of messages, but only if there is an environment value set
- debug:
    msg:
    - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"
    - "These servers were built using the mySQL password of '{{ mysql_root_password }}'. Please retain this for later use."
  tags: [ finish ]

