---
- name: Install Redis
  apt:
    pkg: redis-server
    state: present
  with_items:
   - redis

- name: Start redis Service
  service:
    name: redis-server
    state: started
    enabled: true


