---
- name: '--> Define redis_package'
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined
  tags: [ redis, www ]

- name: '--> ensure Redis is installed'
  apt:
    name: "{{ redis_package }}"
    state: present
  tags: [ redis, www ]

- name: '--> ensure Redis is configured'
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis
  tags: [ redis, www ]

- name: '--> ensure Redis is running and enabled on boot'
  service: "name={{ redis_daemon }} state=started enabled=yes"
  tags: [ redis, www ]




