---
- name: install redis on RHEL based distros
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
    - epel-release
    - redis

- name: Start redis Service
  service:
    name: redis
    state: started
    enabled: true

