---
- name: '--> install nginx (Debian)'
  apt:
    name: '{{ nginx_package_name }}'
    state: present
    default_release: '{{ nginx_default_release }}'
    update_cache: yes
  tags: [ nginx, www ]

