---
- name: NGINX | add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_version }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
  tags: [ nginx, www ]


- include_tasks: '{{ ansible_os_family }}.yml'
  tags: [ nginx, www ]


- name: '--> define nginx_user'
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags: [ nginx, www ]


# Vhost configuration.
- import_tasks: vhosts.yml
  tags: [ nginx, www ]

# Nginx setup.
- name: '--> copy nginx configuration in place'
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx
  tags: [ nginx, www ]

- name: '--> ensure nginx service is running as configured'
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  tags: [ nginx, www ]





