---
- name: '--> apt install (Debian)'
  apt:
    name: rsyslog
    state: latest
    install_recommends: '{{ install_recommends }}'
  when: rsyslog_install|bool
  tags: [ common, rsyslog ]

#- name: '--> create Directory for logs'
#  file: path={{ rsys_dir }} owner=root group=root mode=0644 state=directory
#  tags: [ common, rsyslog ]

#- name: RSYSLOG | Copy Rsyslog Conf
#  template: src=rsyslog.j2 dest={{ rsys_conf }} owner=root group=root mode=0644
#  notify:
#   - restart rsyslog
#  tags: [ common, rsyslog ]

- name: '--> start rsyslog service'
  service: name=rsyslog state=started enabled=true
  tags: [ common, rsyslog ]


