---
- name: RSYSLOG | apt install (Debian)
  apt:
    name: rsyslog
    state: latest
  when: rsyslog_install|bool
  tags: [ common, rsyslog ]

#- name: RSYSLOG | Create Directory for logs
#  file: path={{ rsys_dir }} owner=root group=root mode=0644 state=directory
#  tags: [ common, rsyslog ]

#- name: RSYSLOG | Copy Rsyslog Conf
#  template: src=rsyslog.j2 dest={{ rsys_conf }} owner=root group=root mode=0644
#  notify:
#   - restart rsyslog
#  tags: [ common, rsyslog ]

- name: RSYSLOG | Start rsyslog Service
  service: name=rsyslog state=started enabled=true
  tags: [ common, rsyslog ]
