---

- hosts: all
  roles:
  -
    role: common
    tags: [init, common]

- hosts: all
  user: root
  roles:
  -
    role: rsyslog
    tags: [init, rsyslog]
  -
    role: nginx
    tags: [www, nginx]
  -
    role: php
    tags: [www, php]
  -
    role: phpmyadmin
    tags: [www, phpmyadmin]
  -
    role: redis
    tags: [init, redis]
  -
    role: mariadb
    tags: [mysql, mariadb]
  -
    role: finish
    tags: [end, finish]

