---
- name: check if nginx is installed
  stat:
    path: /etc/nginx/conf.d
  changed_when: false
  register: nginx_conf_dir

- name: Create a symbolic link to web-interface
  file:
    src: /usr/share/phpmyadmin
    dest: /var/www/html/phpmyadmin
    owner: root
    group: root
    state: link


#- name: ensure phpmyadmin configuration for nginx is installed
#  template:
#    src: nginx.conf.j2
#    dest: /etc/nginx/conf.d/phpmyadmin.conf
#  notify: reload nginx
#  when: nginx_conf_dir.stat.exists
