---
- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_databases }}"
  tags: [ mysql ]


#- name: Import Database
#  mysql_db: name={{database_name}} login_host={{hostname}} login_user={{mysql_user}} login_password={{mysql_password}} state=import target=/tmp/{{database_name}}.sql.gz
#  tags: [ mysql ]

#- name: Remove the .sql.gz file
#  file: path=/tmp/{{database_name}}.sql.gz state=absent
#  tags: mysql
