---
- name: '--> check if MySQL is already installed'
  stat: path=/etc/init.d/mysql
  register: mysql_installed
  tags: [ mysql ]

- name: '--> update apt cache if MySQL is not yet installed'
  apt:
    update_cache: yes
  when: not mysql_installed.stat.exists
  tags: [ mysql ]

- name: '--> install MySQL Python libraries'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ mysql_python_package_debian }}'
  when: mysql_install|bool
  tags: [ mysql ]

- name: '--> install MySQL packages'
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: '{{ install_recommends }}'
  with_items:
    - '{{ mysql_packages }}'
  register: deb_mysql_install_packages
  when: mysql_install|bool
  tags: [ mysql ]

# Because Ubuntu starts MySQL as part of the install process, we need to stopmysql and remove the logfiles in case the user set a custom log file size.
- name: '--> ensure MySQL is stopped after initial install'
  service: 'name={{ mysql_daemon }} state=stopped'
  when: not mysql_installed.stat.exists
  tags: [ mysql ]

- name: '--> delete innodb log files created by apt package after initial install'
  file: path={{ mysql_datadir }}/{{ item }} state=absent
  with_items:
    - ib_logfile0
    - ib_logfile1
  when: not mysql_installed.stat.exists
  tags: [ mysql ]


