---
- name: '--> install ufw'
  apt:
    name: ufw
    install_recommends: '{{ install_recommends }}'
  when: ufw_enabled|bool
  tags: [ common, ufw ]

- name: '--> deny all other incoming traffic by default'
  ufw:
    policy: deny
    direction: incoming
  tags: [ common, ufw ]

- name: '--> allow ssh & www connections'
  ufw:
    rule: allow
    state: enabled
    name: '{{ item }}'
  with_items:
    - SSH
    - WWW
  tags: [ common, ufw ]

- name: '--> stop spam ufw logs to system logs'
  lineinfile:
    path: /etc/rsyslog.d/20-ufw.conf
    state: present
    regexp: '^#?& stop'
    line: '& stop'
  notify: restart rsyslog
  tags: [ common, ufw ]

# PORTs VERSION
#- name: '--> initial setup of firewall (tcp)'
#  ufw:
#    rule: allow
#    proto: tcp
#    to_port: '{{ item }}'
#  with_items:
#    - ftp
#    - ssh
#    - http
#    - https
#    - ssmtp
#    - smtp
#    - pop3
#    - pop3s
#    - imap
#    - imaps
#    - domain
#  tags: [ common, ufw ]

#- name: '--> initial setup of firewall (udp)'
#  ufw:
#    rule: allow
#    proto: udp
#    to_port: '{{ item }}'
#  with_items:
#    - domain
#  tags: [ common, ufw ]

