---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata


- name: restart sshd
  become: "{{ sshd_become }}"
  become_user: "{{ sshd_become_user }}"
  service:
    name: ssh
    state: restarted
  notify: wait for reconnect

- name: 'wait for reconnect'
  wait_for_connection:

