---
- name: Update repository and ugprade OS to latest
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400
  tags: common

- name: Install required python packages
  apt:
    name:
      ["python3-pip", "python3-apt"]
    state: present
  tags: common

- name: Install some utilities that all servers benefit from and most of our scripts require
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - unzip
    - imagemagick
    - bzip2
    - pkg-config
    - ufw
    - htop
    - wget
    - curl
    - locales
  # sudo: yes
  tags: common

  # Install firewall and initial setup
- name: Initial Setup of firewall (tcp)
  ufw:
    rule: allow
    proto: tcp
    to_port: "{{ item }}"
  with_items:
    #- ftp
    - ssh
    - http
    #- https
    #- ssmtp
    #- smtp
    #- pop3
    #- pop3s
    #- imap
    #- imaps
    #- domain
  tags: common

- name: Initial setup of firewall (udp)
  ufw:
    rule: allow
    proto: udp
    to_port: "{{ item }}"
  with_items:
    - domain
  tags: common

- name: Create locale en_US.UTF-8
  template:
    src: locale
    dest: /etc/default/locale
  tags: common

