---
- name: '--> Update repository and ugprade OS to latest (Debian)'
  apt:
    # name: '*'
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400
    state: latest
    install_recommends: '{{ install_recommends }}'
  tags: [ common, apt ]

- name: '--> install common system packages: {{ common_packages }}'
  apt:
    name: '{{ common_packages }}'
    state: latest
    install-recommends: '{{ install_recommends }}'
  tags: [ common ]

# !!! need to be installed 'locales' package for this task
- name: '--> ensure a "{{ locale }}" locale exists'
  locale_gen:
    name: '{{ locale }}'
    state: present
  register: locales_done
  tags: [ common ]

- name: '--> set timezone to "{{ timezone }}"'
  timezone:
    name: '{{ timezone }}'
  # changed_when: current_zone.stdout != '{{ timezone }}'
  notify:
    - update timezone
  register: timezone_done
  tags: [ common ]

#- name: '--> correct LocalTime'
#  file:
#    src: /usr/share/zoneinfo/Europe/Kiev
#    dest: /etc/localtime
#    state: hard
#  tags: [ common ]

# Sudo Group Setup
- name: '--> make sure we have a "wheel" group'
  group:
    name: wheel
    state: present
  tags: [ common, user ]

- name: '--> allow "wheel" group to have passwordless sudo'
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  tags: [ common, user ]

# User + Key Setup
- name: '--> create a new regular user with sudo privileges'
  user:
    name: '{{ create_user }}'
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash
  tags: [ common, user ]

- name: '--> set authorized key for remote user'
  authorized_key:
    user: '{{ create_user }}'
    state: present
    key: "{{ copy_local_key|default(lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub')) }}"
  tags: [ common, user ]





