- name: Install php{{ php_version }} with php{{ php_version }}-fpm & php{{ php_version }}-redis
  apt:
    name: ["php{{ php_version }}", "php{{ php_version }}-fpm", "php{{ php_version }}-redis"]
    state: present
  notify: restart php

#- name: Restart php{{ php_version }}-fpm
#  service:
#    name: 'php{{ php_version }}-fpm'
#    state: restarted
#    enabled: yes
